# See https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      version: "62.x"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    additionalPrometheusRulesMap:
      rule-name:
        groups:
        - name: test-alerts
          rules:
          - alert: TestAlert
            expr: vector(1)
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "This is a test alert"
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - alerts.local
      config:
        global:
          resolve_timeout: 1m
          pagerduty_url: "https://events.eu.pagerduty.com/v2/enqueue"
        receivers:
          - name: pagerduty-service-prometheus-test
            pagerduty_configs:
            - service_key: R03E5FXGHY52UNTGBOZI79AUUPMO832S
          - name: webhook-test
            webhook_configs:
            - url: https://webhook.site/0d65b86a-edcc-4394-b6d4-a3201fad4420
        route:
          group_by: [cluster]
#          receiver: pagerduty-service-prometheus-test
          receiver: webhook-test
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.local
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.local
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
  postRenderers:
    - kustomize:
        patches:
          - target:
              # Ignore these objects from Flux diff as they are mutated from chart hooks
              kind: (ValidatingWebhookConfiguration|MutatingWebhookConfiguration)
              name: kube-prometheus-stack-admission
            patch: |
              - op: add
                path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                value: disabled
          - target:
              # Ignore these objects from Flux diff as they are mutated at apply time but not at dry-run time
              kind: PrometheusRule
            patch: |
              - op: add
                path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                value: disabled
