apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-cd-secret.enc.yaml
  - ../../base/book-shuffle
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
