apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: book-shuffle
  namespace: book-shuffle
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
      - host: books.devhome.ioab.io
        paths:
        - path: /
          pathType: ImplementationSpecific
