apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:3w0WsG7D0VDRzyXFnxA9dmnmyouFzE8BgI8dgDnRN84TnZK4cS9IxeH2BYRshJLbG1ZKO/OZQLqPXWJniQDPIHzu2yGVRMG4ZKY7GibHwFnFFdGq7Hwk/XOz92jf7eHuET1vMt1UdkVsD1TcihciFRBaELbIX1NEtxTuFGoyh3Aqw5JcFoSLdWcfMRente2cz3H/jaZqmvh97cgSZ7NDWSlDpFxk6z4NLqjXc19KJF7C1SYEsYhzvOnI5dN+EHEfSbioaNqhBm8VwaFRh9lfKg==,iv:2rhf53dqj7F9l3EsOQgd/epGn5BcbOhRj7Xm7eDy9jE=,tag:oYuQim3UFSj8H3Ix/DwoiQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-cr-secret
    namespace: book-shuffle
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-26T13:01:53Z"
    mac: ENC[AES256_GCM,data:PhRKOGJeFWnO/k2mEdV5QNjQ/FRuWEsW/1LH9rsPeEdp0MRy8IuvuSJ2dkmtrO+EYTjU3QYMk2vQKsxcsfS6BuMMPp2Nc6Jc7gFEtDTrLoYEVPJ6iEHxvilllooV/Qi7Vlq4edTTAglXSzwmLBRe9MFdNExRRKpARYppPNnY8L4=,iv:PHtSsenzxwXijwDLtR7OIy/MqEwx6uugajnbVojIaFo=,tag:yesfdN6ZKz3G28vdbgyQ6g==,type:str]
    pgp:
        - created_at: "2024-07-26T13:01:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/UcafiAXV/1ARAApYGm0WxUtdl5yYc2TDHGUmsC4hJXCxgaID9+vPBVYodP
            TJxSOKWVwND7e799ziQ7Ivg13oLS7Tp5Vz7DIueE9zdggeeVq/ONzvmI3UDPmul4
            50yta1MIL/4vDUTcoSHKOxtIMA9g2VEnyvw8ME1JndQis4R8lz8ZDdh7bWeo2dEb
            7v83AZTkz6k7NPsuk3WINmCa3c+Ihm2F0LjahgLPLgMytHObdz4mO3RM7spWihva
            d/QsRLc/X2JRhEDdQPaYH5YSFOiSiBSPcWO1WJi4tzScbuzmk9rI/jRJsejCkEzc
            oO9NusDGD04RoyQnzA814FGzISnBRN4IlAiH+KEBL8/rgGmlAoqt1ym/kyR7gpYx
            A5fgQhMCxFJgsHahtO7hE84/uwLFSJ2iW1faiVg7l4XnduPw65I8eOSFLmsR7w6X
            DxiWGcc/jdvnPRtSZa2qyuGQRLV0IhPpGbHeSLzC/Zd/mc8JvYSjIuyFwMY00Mje
            Fw2MAAunAb2iTxZwO8ksLLlBA/gSAkjMtw5BNOquOVI0rwlb5EcMfqhHTqldwYpn
            ITH+t+uFEciCFn9YLlq54E49VGaoUsXvHpIJb3ytxqvzSjlQv52pKadvICEz++wW
            NRq1vMgPm6Jlgw2Dlrr8cbfBdf3S1YbG6PC4DCBe2cXiK1TbiKwdnLo3Sx1oeZzS
            XgHI3rSAXlkqaWYtWPcz0Q9K8UjC4G6qSmVOiAlH2/BXRU8JI0FDOqnrFXM0g9qH
            Vy/dte1RMgDtDTJAqnthebRhQeoVMaiO1XLvhGAQHRoBgUgd6rnvwqhf5KJNUkg=
            =47Ig
            -----END PGP MESSAGE-----
          fp: 50A503DBAE542B1B86C935F2094013E8E9B735E5
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
