apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: book-shuffle
  namespace: book-shuffle
spec:
  releaseName: book-shuffle
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: generic-helm-chart
        namespace: common
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/al-v-in/book-shuffle
      tag: main-9c5dcc58-1729265824 # {"$imagepolicy": "book-shuffle:book-shuffle:tag"}
    imagePullSecrets:
    - name: github-cr-secret
