name: Auto-PR
on:
  create:
    branches: ['flux-image-updates']

permissions:
  pull-requests: write

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - name: pull-request
      run: |
        gh_pr_up() { gh pr create $* || gh pr edit $* }
        gh_pr_up --title "Flux image update" --body "Automated PR"
